name: CI

on:
  push:
    branches:
      - 'main'
      - 'release-*'
      - 'wip-*'
    tags:
      - 'v*'
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  schedule:
    - cron: '0 3 * * 1' # Mondays at 3am

env:
  node-version: '14.x'
  CI: true
  GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Prepare
        run: ./.github/scripts/setup-ci.sh
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Run Tests
        run: yarn test:ember

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Prepare
        run: ./.github/scripts/setup-ci.sh
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: yarn test:ember

  build:
    name: Build Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Prepare
        run: ./.github/scripts/setup-ci.sh
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Install template app dependencies
        working-directory: ./build-tests/app-template
        run: yarn install --frozen-lockfile --non-interactive
      - name: Run Tests
        run: yarn test:build

  try-scenarios:
    name: "Scenario: ${{ matrix.try-scenario }} | optional: ${{ matrix.allow-failure }}"
    runs-on: ubuntu-latest
    needs: [test, build, floating]
    continue-on-error: ${{ matrix.allow-failure }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.28
          - ember-lts-4.4
          - ember-release
          - ember-beta
          - ember-classic
        allow-failure: [false]
        include:
          - scenario: ember-canary
            allow-failure: true
          - scenario: embroider-safe
            allow-failure: true
          - scenario: embroider-optimized
            allow-failure: true

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Prepare
        run: ./.github/scripts/setup-ci.sh
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
